INSERT INTO public.autor
(dt_nascimento, dt_ultima_atualizacao, id, id_usuario_ultima_atualizacao, nacionalidade, nome, dt_cadastro)
VALUES
-- 📖 Brasileiros
('1839-06-21', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Machado de Assis', NOW()),
('1920-12-10', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Clarice Lispector', NOW()),
('1912-09-17', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Jorge Amado', NOW()),
('1892-10-20', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Mário de Andrade', NOW()),
('1901-06-27', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Graciliano Ramos', NOW()),
('1908-01-27', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Guimarães Rosa', NOW()),
('1906-11-07', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Cecília Meireles', NOW()),
('1905-02-19', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Vinícius de Moraes', NOW()),
('1866-09-20', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Olavo Bilac', NOW()),
('1836-08-21', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Castro Alves', NOW()),
('1881-08-13', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Monteiro Lobato', NOW()),
('1897-12-13', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Manuel Bandeira', NOW()),
('1913-03-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Rubem Braga', NOW()),
('1912-10-16', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Rachel de Queiroz', NOW()),
('1918-03-14', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Carlos Drummond de Andrade', NOW()),
('1946-10-17', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Chico Buarque', NOW()),
('1920-10-23', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Érico Veríssimo', NOW()),
('1958-08-24', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Luis Fernando Verissimo', NOW()),
('1957-07-20', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Paulo Coelho', NOW()),
('1941-10-30', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Ferreira Gullar', NOW()),
('1956-03-29', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Cristovão Tezza', NOW()),
('1959-02-27', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Conceição Evaristo', NOW()),
('1961-01-01', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Milton Hatoum', NOW()),
('1957-09-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Raduan Nassar', NOW()),
('1972-03-10', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Daniel Galera', NOW()),
('1960-05-18', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Adélia Prado', NOW()),
('1970-11-15', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Marçal Aquino', NOW()),
('1964-04-03', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Ana Maria Machado', NOW()),
('1960-07-07', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'João Ubaldo Ribeiro', NOW()),
('1978-08-22', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'André Vianco', NOW()),
('1975-02-05', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Carola Saavedra', NOW()),
('1986-01-15', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Vanessa Barbara', NOW()),
('1969-09-17', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Tatiana Salem Levy', NOW()),
('1980-04-09', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Raphael Montes', NOW()),
('1986-11-14', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Socorro Acioli', NOW()),
('1973-05-19', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Marcelo Rubens Paiva', NOW()),
('1982-06-10', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Michel Laub', NOW()),
('1976-10-23', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Daniel Pellizzari', NOW()),
('1983-02-08', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Patrícia Melo', NOW()),
('1974-01-29', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'João Anzanello Carrascoza', NOW()),
('1981-07-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Julián Fuks', NOW()),
('1968-09-25', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Lygia Fagundes Telles', NOW()),
('1979-11-06', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Marina Colasanti', NOW()),
('1985-08-08', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Carolina Munhóz', NOW()),
('1971-02-17', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'André Sant’Anna', NOW()),
('1967-03-30', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Reinaldo Moraes', NOW()),
('1984-09-02', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Luisa Geisler', NOW()),
('1950-06-14', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileiro', 'Ignácio de Loyola Brandão', NOW()),
('1962-10-22', NOW(), gen_random_uuid(), gen_random_uuid(), 'Brasileira', 'Hilda Hilst', NOW()),

-- 🌍 Internacionais
('1564-04-26', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglês', 'William Shakespeare', NOW()),
('1812-02-07', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglês', 'Charles Dickens', NOW()),
('1775-12-16', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglesa', 'Jane Austen', NOW()),
('1818-08-30', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglesa', 'Mary Shelley', NOW()),
('1890-09-15', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglesa', 'Agatha Christie', NOW()),
('1892-01-03', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglês', 'J. R. R. Tolkien', NOW()),
('1903-06-25', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglês', 'George Orwell', NOW()),
('1928-01-19', NOW(), gen_random_uuid(), gen_random_uuid(), 'Inglesa', 'Penelope Lively', NOW()),
('1828-09-09', NOW(), gen_random_uuid(), gen_random_uuid(), 'Russo', 'Leo Tolstói', NOW()),
('1821-11-11', NOW(), gen_random_uuid(), gen_random_uuid(), 'Russo', 'Fiódor Dostoiévski', NOW()),
('1891-07-03', NOW(), gen_random_uuid(), gen_random_uuid(), 'Russo', 'Boris Pasternak', NOW()),
('1881-09-15', NOW(), gen_random_uuid(), gen_random_uuid(), 'Russo', 'Alexander Blok', NOW()),
('1927-03-06', NOW(), gen_random_uuid(), gen_random_uuid(), 'Colombiano', 'Gabriel García Márquez', NOW()),
('1942-11-07', NOW(), gen_random_uuid(), gen_random_uuid(), 'Argelino-Francês', 'Albert Camus', NOW()),
('1802-02-26', NOW(), gen_random_uuid(), gen_random_uuid(), 'Francês', 'Victor Hugo', NOW()),
('1821-07-08', NOW(), gen_random_uuid(), gen_random_uuid(), 'Francês', 'Charles Baudelaire', NOW()),
('1844-03-24', NOW(), gen_random_uuid(), gen_random_uuid(), 'Francês', 'Paul Verlaine', NOW()),
('1842-12-11', NOW(), gen_random_uuid(), gen_random_uuid(), 'Francês', 'Émile Zola', NOW()),
('1913-07-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Francês', 'Albert Cohen', NOW()),
('1749-08-28', NOW(), gen_random_uuid(), gen_random_uuid(), 'Alemão', 'Johann Wolfgang von Goethe', NOW()),
('1813-10-15', NOW(), gen_random_uuid(), gen_random_uuid(), 'Alemão', 'Georg Büchner', NOW()),
('1883-07-03', NOW(), gen_random_uuid(), gen_random_uuid(), 'Tcheco', 'Franz Kafka', NOW()),
('1805-04-02', NOW(), gen_random_uuid(), gen_random_uuid(), 'Dinamarquês', 'Hans Christian Andersen', NOW()),
('1847-07-30', NOW(), gen_random_uuid(), gen_random_uuid(), 'Emily Brontë', 'Inglesa', NOW()),
('1818-07-30', NOW(), gen_random_uuid(), gen_random_uuid(), 'Charlotte Brontë', 'Inglesa', NOW()),
('1899-07-21', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'Ernest Hemingway', NOW()),
('1929-01-19', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'Patricia Highsmith', NOW()),
('1954-08-24', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'Orson Scott Card', NOW()),
('1929-01-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'Martin Luther King Jr.', NOW()),
('1932-09-21', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'Stephen King', NOW()),
('1899-12-01', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'William Faulkner', NOW()),
('1925-09-20', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'Truman Capote', NOW()),
('1896-12-24', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'F. Scott Fitzgerald', NOW()),
('1930-05-31', NOW(), gen_random_uuid(), gen_random_uuid(), 'Americano', 'John Barth', NOW()),
('1949-01-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Canadense', 'Margaret Atwood', NOW()),
('1961-08-18', NOW(), gen_random_uuid(), gen_random_uuid(), 'Canadense', 'Douglas Coupland', NOW()),
('1939-07-14', NOW(), gen_random_uuid(), gen_random_uuid(), 'Italiano', 'Umberto Eco', NOW()),
('1908-09-05', NOW(), gen_random_uuid(), gen_random_uuid(), 'Italiano', 'Cesare Pavese', NOW()),
('1922-10-15', NOW(), gen_random_uuid(), gen_random_uuid(), 'Italiano', 'Italo Calvino', NOW()),
('1867-05-18', NOW(), gen_random_uuid(), gen_random_uuid(), 'Norueguês', 'Knut Hamsun', NOW()),
('1828-07-24', NOW(), gen_random_uuid(), gen_random_uuid(), 'Norueguês', 'Henrik Ibsen', NOW()),
('1911-06-25', NOW(), gen_random_uuid(), gen_random_uuid(), 'Japonês', 'Yasunari Kawabata', NOW()),
('1949-01-12', NOW(), gen_random_uuid(), gen_random_uuid(), 'Japonês', 'Haruki Murakami', NOW()),
('1927-01-14', NOW(), gen_random_uuid(), gen_random_uuid(), 'Japonês', 'Kenzaburō Ōe', NOW()),
('1933-11-08', NOW(), gen_random_uuid(), gen_random_uuid(), 'Chinês', 'Mo Yan', NOW()),
('1898-02-25', NOW(), gen_random_uuid(), gen_random_uuid(), 'Chinês', 'Lao She', NOW()),
('1960-02-20', NOW(), gen_random_uuid(), gen_random_uuid(), 'Chinês', 'Yu Hua', NOW()),
('1924-09-30', NOW(), gen_random_uuid(), gen_random_uuid(), 'Indiano', 'R. K. Narayan', NOW()),
('1913-02-27', NOW(), gen_random_uuid(), gen_random_uuid(), 'Indiano', 'Khushwant Singh', NOW()),
('1861-05-07', NOW(), gen_random_uuid(), gen_random_uuid(), 'Indiano', 'Rabindranath Tagore', NOW());
